item {
    id: 1
    name: 'Blower'
}item {
    id: 2
    name: 'Dosing Pump'
}item {
    id: 3
    name: 'Fan'
}item {
    id: 4
    name: 'Gate Valve'
}item {
    id: 5
    name: 'Mixer'
}item {
    id: 6
    name: 'On Off Valve'
}item {
    id: 7
    name: 'Pump'
}item {
    id: 8
    name: 'Screening'
}item {
    id: 9
    name: 'Solenoid Valve'
}item {
    id: 10
    name: 'Submersible Pump'
}item {
    id: 11
    name: 'UV'
}
